### ISSUE TITLE
Aktueller Workflow durchspielen inklusive Testcase ausführen

### ISSUE THREAD

**Issue by RoAnBu** [elite-se/plantestic-team-1#10]
https://github.com/RoAnBu/plantestic-tester

**Comment by RoAnBu** [comment]
Repository für Testfälle https://github.com/RoAnBu/plantestic-tester

**Comment by denizcandas** [comment]
This is a guide for Windows users. Hopefully, it works similar enough in Linux.
- Create a puml file manually (maybe http://www.plantuml.com can help, but it just displays what is printed)
- Make sure the puml file complies to the "input requirements" chapter in the readme
- Clone the repo
- Run gradlew.bat build (to execute the tests, which is broken in Windows, so you can skip this too)
- gradlew.bat run --args="--input=/Full/Path/To/Your/Puml/File" (or input=../file.puml if your file is in the root directory) (or input=file.puml if your file is in the core directory)
A file in plantestic\core\plantestic-test will be generated, which has code to test another system. Either:
- Copy this file into a main method and execute that (how?)
- Just like in the end2end tests, use a reflect call to execute the file (but there is a file error in windows, which removes the first letter of the operating system), and make sure to use the testing dependencies for the main folder
- Put the test into its own project and add proper dependencies (see repository for test cases)

Maybe important:
- Gradle is for handling dependencies and building java stuff. When building stuff, gradle automatically runs the tests too. Gradle can build jar files, but it does not include the test cases when building them. The wrappers are scripts which download the dependencies including the required gradle version, thereby allowing any user to build anything if they have java installed. This wrapper is gradlew for linux users and gradlew.bat for windows users.
- All the code seems to be written in kotlin.
- Because jars do not include test cases, and because we only need to run one test case in the main method, it could be a better idea to rewrite the desired test case into the main method so that it can be exported as a jar file. However, this means that gradle dependencies have to be recompiled properly (implementation instead of testImplementation, etc.).

**Comment by denizcandas** [comment]
![image](https://user-images.githubusercontent.com/16650999/87221406-1c7c1680-c36c-11ea-8068-a313a85baa49.png)
How using reflect in a method might look like
